# Site settings
title: 404 Fab Academy student not found
email: bettygorf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bettygorf's unofficial page for Fab Academy 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bettygorf
github_username:  bettygorf

# Build settings
markdown: kramdown
