# Site settings
title: bettygorf
email: bettygorf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  home of bettygorf
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bettygorf
github_username:  bettygorf

# Build settings
markdown: kramdown
